# Generated by Django 5.0.6 on 2026-08-01 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('license_key', models.TextField(unique=True)),
                ('status', models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('suspended', 'Suspended')], default='inactive', max_length=20)),
                ('device_id', models.TextField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('product_name', models.CharField(default='General', max_length=200)),
                ('license_type', models.CharField(choices=[('trial', 'Trial'), ('standard', 'Standard'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='standard', max_length=20)),
                ('max_activations', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'licenseslist',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=50)),
                ('license_key', models.TextField(blank=True, default='')),
                ('details', models.JSONField(blank=True, default=dict)),
                ('performed_by', models.CharField(default='system', max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='licenses.license')),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
